### PR TITLE
[Reviewer: Alex] Move to config-package infrastructure

### PR DESCRIPTION
**Pull request by rkd-msw**
Hi Alex,

This moves clearwater-cassandra over to the structured config-package infrastructure (https://debathena.mit.edu/config-packages/) instead of just running random sed scripts. That approach caused issues on upgrade if we change a config file that has also changed upstream (#16).

I strongly recommend you review commit-by-commit - I've tried to make that sensible (e.g. by pulling in files from Cassandra and modifying them in separate commits). In particular, I think you'll barely need to review https://github.com/Metaswitch/clearwater-cassandra/commit/b808fa7ee2bc205f32de5eeece2cc13c7abc4af8.

So that you don't get confused, I haven't been able to exactly follow my emailed proposal - in particular, I was wrong about how transform rules work. They don't transform files on the production system at install time - they transform files on the build system at package creation time - so the use-case there is "check in a standard version of a file, use the transform rule to tweak it to your needs". Instead, I've just checked in the file, modified it and used a displace rule to put it into place - i think just editing the file is generally going to be easier than writing/deciphering the sed commands to modify it.

Ultimately all this does is:

* replaces /etc/init.d/cassandra with a version that runs in the signaling namespace
* replaces /etc/default/cassandra and /usr/share/cassandra/cassandra.in.sh with a version that always uses Java 7 (we didn't need to do the latter through this mechanism, as it's not a conffile, but on reflection I thought it was best to be consistent in how to change those files)
* replaces /etc/cassandra/cassandra-env.sh with an IPv4-enabled or IPv6-enabled version, based on the type of $local_ip
* hides /etc/cassandra/cassandra.yaml and /etc/cassandra/cassandra-rackdc.properties so that clearwater-cluster-manager can generate them

There are two things I thought of doing while making this change, but which ultimately didn't seem worth it:
- Instead of checking in files from the Cassandra repository and modifying them, I could have included Cassandra as a submodule, defined a Makefile rule that would copy the files into the right directory, and defined transform rules to make the corresponding edits. In principle this would mean that we could change our submodule to point at a different Cassandra version and everything would auto-update, but it felt like overkill.
- I considered moving a lot of the cassandra.yaml-mangling logic out from the plugin into a script which the plugin could run with some arguments - especially given that there's currently a bit that shells out to check an /etc/clearwater/config value. I couldn't quite persuade myself it was worth the risk of the change, but I'd like a second opinion.

Two things I'm not doing in this PR, because they're nicely separable:
* add a clearwater-cluster-manager hook we can kick to regenerate the cassandra.yaml file when the template changes
* move AIO and Docker nodes over to use etcd

Let me know if you're really keen to review either of those follow-on PRs, otherwise I might spread the load.

### CODE REVIEW

**Comment by AlexHockey** [comment]
No huge comments on the substance of what you've done. but we're pretty deep into debian packaging shenanigans so I have suggested you add a few more comments. 

> Instead of checking in files from the Cassandra repository and modifying them, I could have included Cassandra as a submodule, defined a Makefile rule that would copy the files into the right directory, and defined transform rules to make the corresponding edits. In principle this would mean that we could change our submodule to point at a different Cassandra version and everything would auto-update, but it felt like overkill.

I definitely don't think we should have Cassandra as a submodule. When we do upgrade Cassandra how do we merge our changes into the new versions of their files? Should we mark our changes with `#clearwater-specific change start/end`? Or should we also check in the original unmodified files to use as a merge base?

> I considered moving a lot of the cassandra.yaml-mangling logic out from the plugin into a script which the plugin could run with some arguments - especially given that there's currently a bit that shells out to check an /etc/clearwater/config value. I couldn't quite persuade myself it was worth the risk of the change, but I'd like a second opinion.

Agree it's not worth the change. Note that when we move over to proper config files this kind of thing should seem a lot less hokey.

I'm happy to review the follow-on PRs given I have more context.

**Comment by rkd-msw** [comment]
Can you check that https://github.com/Metaswitch/clearwater-cassandra/commit/0116424e624f10fc375525d73101914c1bc69ac0 addresses all your feedback?

Specific notes:

* I've made postinst restart cassandra, and made sure that happens after the autogenerated debhelper code
* The changes to Cassandra's files are easily expressible, so I've documented them in the README - listing what we've done and why feels much more future-proof than trying to do a merge.

**Comment by rkd-msw** [comment]
Oh, yeah, I've tested this:

* on a fresh install , everything is nice, calls work and `debsums -ce` doesn't report any Cassandra files as being illicitly modified
* on an upgrade, we upgrade cleanly without being asked any questions about conflicts. `debsums -ce` still reports the Cassandra files as being modified (because the old code modified them before the new code diverted them):

```
$ sudo debsums -ce
/etc/bash.bashrc
/etc/skel/.bashrc
/usr/share/clearwater-cassandra/etc++cassandra++cassandra-rackdc.properties
/etc/default/cassandra.clearwater-orig
/usr/share/clearwater-cassandra/etc++cassandra++cassandra.yaml
/etc/default/rcS
debsums: missing file /etc/nginx/sites-available/default (from nginx-common package)
/etc/snmp/snmpd.conf
```

If we had to take a new Cassandra version urgently, I think we could just run `sudo apt-get -o DPkg::options::=--force-confnew install cassandra` safely.

I haven't made test calls after an upgrade because that won't work - clearwater-cassandra hides /etc/cassandra/cassandra.yaml, but I haven't written the code to kick cluster manager to regenerate it. I won't merge this until the follow-on code is ready, and I'll test again when it's all in place.

**Comment by AlexHockey** [comment]
As discussed, I think it would be useful to test that this works when we actually upgrade cassandra, and you thought that wouldn't be too difficult, so you are going to do this test.

**Comment by rkd-msw** [comment]
OK, might be worth you checking my markups (https://github.com/Metaswitch/clearwater-cassandra/pull/79/commits/de50894b56b399f04cc38cbee617fb24da99762a) for safety's sake, but this is ready to merge once I figure out how it should work with clearwater-docker.

**Comment by rkd-msw** [comment]
I tweaked /etc/default/cassandra, bumped the version and rebuilt Cassandra. With the master code, I get a conflict reported:

```
Setting up cassandra (2.0.15) ...
Installing new version of config file /etc/init.d/cassandra ...

Configuration file '/etc/default/cassandra'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
 ==> Keeping old config file as default.
```

(I was using clearwater-upgrade, which includes `--force-confdef -o Dpkg::Options::=--force-confnew`, so doesn't ask the user.)

With my new code, no such conflict, and we can see evidence of the diversion:

```
Setting up cassandra (2.0.15) ...
Installing new version of config file /etc/init.d/cassandra.clearwater-orig ...
Installing new version of config file /etc/default/cassandra.clearwater-orig ...
vm.max_map_count = 1048575
Processing triggers for ureadahead (0.100.0-16) ...
Processing triggers for python-support (1.0.15) ...
```

**Pull request merged**
