### PR TITLE
[Reviewer: Ellie] Use Java 7 when Cassandra 2.0.14 is installed

### PR DESCRIPTION
**Pull request by rkd-msw**
I've upgraded a node from Cassandra 1.2 to 2.0, and confirmed that it comes up without further manual tweaks.

### CODE REVIEW

**Comment by eleanor-merry** [comment]
@bossmc - you had various comments on this, so passing over to you

**Comment by bossmc** [comment]
`update-alternatives` is system-wide and non-sticky so it's not a good solution.

According to http://wiki.apache.org/cassandra/RunningCassandra this should be done by setting `JAVA_HOME` in `/etc/default/cassandra` for Debian systems.

**Comment by rkd-msw** [comment]
@bossmc, I think what we agreed (reluctantly) when we discussed was:

* add JAVA_HOME to /etc/default/cassandra
* add JAVA_HOME to /usr/share/cassandra/cassandra.in.sh, so `nodetool` uses Java 7
* strongly recommend running `update-alternatives --set java /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java` on migration, so that freshly-installed systems (which will just pick up Java 7) and upgraded ones have the same config ( @eleanor-merry , one for your upgrade doc?)

You suggested making clearwater-cassandra conflict with Java 6, but I don't think that's necessary (and might be unhelpful if users have e.g. Java monitoring daemons installed).

**Comment by bossmc** [comment]
Sounds right to me.

**Comment by rkd-msw** [comment]
Tested by spinning up a Cassandra 1.2 Homer node, upgrading, and checking that:
* Cassandra used Java 7 and came up OK
* `nodetool status` ran
* `java -version` reported that the system default was still Java 6

**Pull request merged**
